version: '3.7'

services: 
    db:
        image: mariadb:latest
        restart: always
        container_name: db-conte3
        # ホスト名を明示的に指定する
        hostname: db3

        ports: 
            - 3306:3306
        volumes:
            - ./mariadb/db_data:/var/lib/mysql
            - ./mariadb/config_files/initdb.d:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=tic2020-root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=tic2020
            - MYSQL_DATABASE=tic_db
            - TZ=Asia/Tokyo
        command: 
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci

    db-client:
        image: adminer
        restart: always
        container_name: db-client-conte3
        # ホスト名を明示的に指定する
        hostname: db-client3
        ports:
            - 8080:8080

    web-app:
        build:
            ./react/.
        image: react_dev:beta
        tty: true
        restart: always
        container_name: web-app-conte3
        # ホスト名を明示的に指定する
        hostname: web-app3
        ports: 
            - 20023:20022
            - 30001:30000    